Repository refactor-group/refactor-platform-rs, pull requests merged in 2024-07, with the labels that each got.

#50 Add coaching sessions endpoint
  docs/db/refactor_platform_rs.dbml
  entity/src/coaching_sessions.rs
  entity_api/src/coaching_session.rs
  entity_api/src/lib.rs
  migration/src/refactor_platform_rs.sql
  web/src/controller/coaching_session_controller.rs
  web/src/controller/mod.rs
  web/src/router.rs
Labels: enhancement

#52 Update README adding some polish
  README.md
Labels: documentation

#53 Add basic infrastructure for notes API
  entity/src/notes.rs
  entity_api/src/lib.rs
  entity_api/src/note.rs
  web/src/controller/mod.rs
  web/src/controller/note_controller.rs
  web/src/router.rs
Labels: feature work

#54 Add the ability to update note records
  entity/src/notes.rs
  entity_api/src/note.rs
  web/src/controller/note_controller.rs
  web/src/router.rs
Labels: feature work

#55 Set coaching_session_id and user_id for the POST/PUT Notes endpoints
  Cargo.lock
  entity/Cargo.toml
  entity/src/notes.rs
  entity_api/Cargo.toml
  web/Cargo.toml
  web/src/controller/note_controller.rs
Labels: enhancement

#56 Handle a failed DBConnection better instead of an unwrap() panic
  src/main.rs
Labels: bug, enhancement
