Repository refactor-group/refactor-platform-rs, pull requests merged in 2024-12, with the labels that each got.

#79 Deserialize just the right fields when creating new entities
  entity/src/actions.rs
  entity/src/coachees.rs
  entity/src/coaches.rs
  entity/src/coaching_relationships.rs
  entity/src/coaching_sessions.rs
  entity/src/organizations.rs
  entity/src/users.rs
  web/src/controller/user_controller.rs
Labels: enhancement

#80 Add a new docker-compose service for our Next.js frontend application
  docker-compose.yaml
Labels: enhancement, feature work

#85 select distinct organizations
  entity_api/src/organization.rs
Labels: bug fix

#86 Enable the use of .env for setting runtime variables and non-static setting of CORS allow_origins
  Cargo.lock
  Dockerfile
  docker-compose.yaml
  docs/runbooks/Container-README.md
  service/Cargo.toml
  service/src/config.rs
  web/src/lib.rs
Labels: enhancement

#88 All environment variables for the dockerized backend/frontend applica…
  docker-compose.yaml
  docs/runbooks/Container-README.md
Labels: enhancement

#89 Fix overarching goals and actions not saving
  docs/db/refactor_platform_rs.dbml
  migration/src/refactor_platform_rs.sql
Labels: bug fix

#93 scope coaching_relationships query by user_id
  entity_api/src/coaching_relationship.rs
  web/src/controller/organization/coaching_relationship_controller.rs
Labels: bug fix
