Repository refactor-group/refactor-platform-rs, pull requests merged in 2024-09, with the labels that each got.

#64 Remove status and status_changed_at fields for Agreements entity model
  docs/db/refactor_platform_rs.dbml
  docs/db/refactor_platform_rs.png
  entity/README.md
  entity/src/agreements.rs
  entity_api/src/agreement.rs
  migration/src/refactor_platform_rs.sql
Labels: enhancement

#65 Delete agreement by its Id
  entity_api/src/agreement.rs
  web/src/controller/agreement_controller.rs
  web/src/router.rs
Labels: enhancement

#66 Update statuses
  docs/db/refactor_platform_rs.dbml
  docs/db/refactor_platform_rs.png
  entity/src/overarching_goals.rs
  entity/src/status.rs
  entity_api/src/action.rs
  entity_api/src/overarching_goal.rs
  migration/src/refactor_platform_rs.sql
  web/src/controller/action_controller.rs
  web/src/controller/overarching_goal_controller.rs
  web/src/router.rs
Labels: feature work

#67 Improve Action update behavior, and add the ability to delete an action
  docs/db/refactor_platform_rs.dbml
  docs/db/refactor_platform_rs.png
  entity/src/actions.rs
  entity_api/src/action.rs
  migration/src/refactor_platform_rs.sql
  web/src/controller/action_controller.rs
  web/src/controller/organization_controller.rs
  web/src/router.rs
Labels: enhancement, feature work
