Repository refactor-group/refactor-platform-rs, pull requests merged in 2025-05, with the labels that each got.

#129 Use sea orm migrations
  Cargo.lock
  Dockerfile
  docker-compose.yaml
  entrypoint.sh
  migration/Cargo.toml
  migration/README.md
  migration/src/lib.rs
  migration/src/m20250509_164646_add_initial_non_prod_user.rs
  migration/src/refactor_platform_rs.sql
  scripts/rebuild_db.sh
  service/src/config.rs
Labels: infrastructure

#131 provide platform for migrator service docker-compose
  docker-compose.yaml
Labels: infrastructure

#132 Small improvements
  domain/src/coaching_session.rs
  domain/src/error.rs
  domain/src/gateway/tiptap.rs
  domain/src/jwt/mod.rs
  domain/src/user.rs
  entity_api/src/coaching_relationship.rs
  entity_api/src/error.rs
  entity_api/src/mutate.rs
  entity_api/src/organization.rs
  web/src/error.rs
Labels: enhancement, Refactor

#135 Moves setup.sql into a SeaORM migration
  docker-compose.yaml
  migration/src/lib.rs
  migration/src/m20240210_153056_create_schema_and_base_db_setup.rs
Labels: enhancement, infrastructure

#134 Add a systemd service definition for managing the coaching platform containers start/stop/restart
  docs/runbooks/deploy.md
  service/refactor-platform.service
Labels: enhancement, feature work, infrastructure

#130 118 platform production release deployment from GitHub
  .dockerignore
  .github/workflows/build_and_push_nonproduction_images.yml
  .github/workflows/build_and_push_production_images.yml
  .github/workflows/deploy_to_do.yml
  Cargo.toml
  Dockerfile
  deploy_to_digitalocean_draft.md
  docker-compose.yaml
  entrypoint.sh
  migration/src/m20240210_153056_create_schema_and_base_db_setup.rs
Labels: feature work, infrastructure

#138 Seed Refactor Group Organization
  migration/src/lib.rs
  migration/src/m20250509_164646_add_initial_non_prod_user.rs
  migration/src/m20250509_164646_add_initial_user.rs
  migration/src/refactor_platform_rs.sql
  migration/src/setup.sql
  migration/src/setup_default_user.sql
Labels: infrastructure
