Repository refactor-group/refactor-platform-rs, pull requests merged in 2025-03, with the labels that each got.

#108 Add a partial update User endpoint
  domain/src/action.rs
  domain/src/agreement.rs
  domain/src/coaching_relationship.rs
  domain/src/coaching_session.rs
  domain/src/lib.rs
  domain/src/overarching_goal.rs
  domain/src/user.rs
  entity_api/src/lib.rs
  entity_api/src/mutate.rs
  entity_api/src/query.rs
  entity_api/src/user.rs
  web/src/controller/user_controller.rs
  web/src/controller/user_session_controller.rs
  web/src/extractors/authenticated_user.rs
  web/src/lib.rs
  web/src/params/mod.rs
  web/src/params/user.rs
  web/src/router.rs
Labels: enhancement

#109 Update Coaching Sessions
  domain/src/coaching_session.rs
  entity/src/coaching_sessions.rs
  entity/src/users.rs
  entity_api/src/mutate.rs
  web/src/controller/coaching_session_controller.rs
  web/src/controller/user_controller.rs
  web/src/params/coaching_session.rs
  web/src/params/user.rs
  web/src/protect/coaching_sessions.rs
  web/src/router.rs
Labels: enhancement

#107 Slugify organization names
  Cargo.lock
  entity/src/coaching_relationships.rs
  entity/src/organizations.rs
  entity/src/users.rs
  entity_api/Cargo.toml
  entity_api/src/coaching_relationship.rs
  entity_api/src/lib.rs
  entity_api/src/organization.rs
  web/src/router.rs
Labels: enhancement

#110 Change logout to be a delete action
  web/src/router.rs
Labels: enhancement

#111 88 feature add member management page
  Cargo.lock
  docs/db/refactor_platform_rs.dbml
  docs/db/refactor_platform_rs.png
  domain/src/user.rs
  entity/src/coaching_relationships.rs
  entity/src/lib.rs
  entity/src/organizations.rs
  entity/src/organizations_users.rs
  entity/src/users.rs
  entity_api/src/lib.rs
  entity_api/src/user.rs
  migration/src/refactor_platform_rs.sql
  web/Cargo.toml
  web/src/controller/organization/mod.rs
  web/src/controller/organization/user_controller.rs
  web/src/params/user.rs
  web/src/protect/mod.rs
  web/src/protect/organizations/mod.rs
  web/src/protect/organizations/users.rs
  web/src/router.rs
Labels: enhancement, feature work

#113 88 feature add member management page create
  domain/src/user.rs
  entity_api/src/coaching_relationship.rs
  entity_api/src/user.rs
  web/src/controller/organization/user_controller.rs
  web/src/controller/user_controller.rs
  web/src/protect/organizations/users.rs
  web/src/router.rs
Labels: feature work
