Repository refactor-group/refactor-platform-rs, pull requests merged in 2025-04, with the labels that each got.

#114 88 feature add member management page delete
  domain/src/user.rs
  entity_api/src/coaching_relationship.rs
  entity_api/src/lib.rs
  entity_api/src/organizations_user.rs
  entity_api/src/user.rs
  web/src/controller/mod.rs
  web/src/controller/organization/user_controller.rs
  web/src/protect/organizations/users.rs
  web/src/router.rs
Labels: feature work

#116 Refactor the backend API to match what the frontend already correctly does for logout
  web/src/controller/user_session_controller.rs
  web/src/router.rs
Labels: enhancement

#115 Delete coaching sessions
  domain/src/coaching_session.rs
  domain/src/gateway/tiptap.rs
  entity/src/jwts.rs
  entity_api/src/coaching_session.rs
  web/src/controller/coaching_session_controller.rs
  web/src/protect/coaching_sessions.rs
  web/src/router.rs
Labels: feature work

#87 82 feature request suggestion create GitHub actions workflow for automating the build and deployments for feature branches
  .github/workflows/build_and_deploy_containers.yml
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  Dockerfile
  README.md
  build_and_run.sh
  docker-compose.yaml
  docs/runbooks/Container-README.md
  entity/Cargo.toml
  entity_api/Cargo.toml
  entrypoint.sh
  migration/Cargo.toml
  service/Cargo.toml
  web/Cargo.toml
Labels: feature work, infrastructure

#119 Update to latest version of openssl and openssl-sys to patch moderate…
  Cargo.lock
  Cargo.toml
Labels: security
