Repository refactor-group/refactor-platform-rs, pull requests merged in 2025-02, with the labels that each got.

#99 Remove timezone from coaching_sessions
  docs/db/refactor_platform_rs.dbml
  docs/db/refactor_platform_rs.png
  entity/src/coaching_sessions.rs
  entity_api/src/coaching_session.rs
  entity_api/src/lib.rs
  migration/src/refactor_platform_rs.sql
Labels: feature work

#100 Add /jwt/generate_collab_token endpoint and JWT generation
  Cargo.lock
  docker-compose.yaml
  docs/runbooks/Container-README.md
  domain/Cargo.toml
  domain/src/coaching_session.rs
  domain/src/error.rs
  domain/src/gateway/tiptap.rs
  domain/src/jwt/claims.rs
  domain/src/jwt/mod.rs
  domain/src/lib.rs
  entity/src/jwt.rs
  entity/src/lib.rs
  entity_api/src/coaching_session.rs
  service/src/config.rs
  web/src/controller/jwt_controller.rs
  web/src/controller/mod.rs
  web/src/lib.rs
  web/src/params/jwt.rs
  web/src/params/mod.rs
  web/src/protect/jwt.rs
  web/src/protect/mod.rs
  web/src/router.rs
Labels: feature work

#102 Refactor parameter typing
  domain/src/agreement.rs
  domain/src/lib.rs
  entity_api/src/agreement.rs
  entity_api/src/lib.rs
  web/src/controller/agreement_controller.rs
  web/src/error.rs
  web/src/params/agreement.rs
  web/src/params/mod.rs
  web/src/protect/agreements.rs
Labels: design

#104 Reduce the number of seeded coaching sessions
  entity_api/src/lib.rs
  migration/src/refactor_platform_rs.sql
Labels: enhancement
