Repository refactor-group/refactor-platform-rs, pull requests merged in 2025-06, with the labels that each got.

#144 Broken single organization
  .github/workflows/build_and_push_nonproduction_images.yml
  .github/workflows/deploy_to_do.yml
  docker-compose.yaml
  service/src/config.rs
  src/bin/seed_db.rs
  web/src/extractors/compare_api_version.rs
  web/src/lib.rs
Labels: bug fix

#146 Move to a multi-layered docker-compose.yaml setup
  deploy_to_digitalocean_draft.md
  docker-compose.dev-staging.yaml
  docker-compose.yaml
  docs/runbooks/Container-README.md
Labels: enhancement, infrastructure

#149 cargo update
  Cargo.lock
Labels: security

#161 Add the beginnings of complete system architecture documentation
  docs/architecture/system_architecture_diagram.md
Labels: documentation, enhancement

#160 Make sure that failed login attempts are returned as 401 Unauthorized
  domain/src/error.rs
  web/src/controller/user_session_controller.rs
  web/src/error.rs
Labels: bug fix

#157 Add authorization and validation checks to coaching relationship crea…
  domain/src/user.rs
  entity/src/coaching_relationships.rs
  entity_api/src/coaching_relationship.rs
  entity_api/src/organization.rs
  migration/src/refactor_platform_rs.sql
  web/src/controller/organization/coaching_relationship_controller.rs
  web/src/controller/organization/user_controller.rs
  web/src/protect/organizations/coaching_relationships.rs
  web/src/protect/organizations/mod.rs
  web/src/router.rs
Labels: feature work
